#!/bin/bash
if [ $# -eq 0 ]; then
    echo "Error: No arguments provided"
    echo "Usage: extract_media_then_rename [7z FILE]"
    echo "Extracts the media file embedded in the [7z FILE] and renames it to the original [7z FILE]"
    exit 1
fi
#runs 7z and extracts all the files starting with media into current directory
unzip $1 -d /tmp/
rm $1
#if that was successful, then rename it to the [7z FILE] or $1 in bash else, fail
if [ $? -eq 0 ]; then
    mv /tmp/media~* $1.tmp.mp4
    mv /tmp/overlay~* $1.tmp.png

    #Get video size
    VSIZE=`ffmpeg -i $1.tmp.mp4 2>&1 | grep Stream | grep -oP ', \K[0-9]+x[0-9]+'`
    #Scale the image
    ffmpeg -i $1.tmp.png -vf scale=$VSIZE $1.scaled.png

    ffmpeg -i $1.tmp.mp4 -i $1.scaled.png -filter_complex "overlay=0:0" $1
    echo OK: media extracted to $1;
    rm $1.tmp.mp4
    rm $1.tmp.png
    rm $1.scaled.png
    exit 0;
else
    echo FAIL;
    exit 1;
fi